import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import i18nConfig from "@/i18nConfig";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: any;
}) {
  console.log("layout", params);
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
